// export const USER = {
//   AUTH: {
//     REQUEST: 'user/REQUEST',
//     FAIL: 'user/FAILED',
//     SUCCESS: 'user/SIGNING_SUCCESS',
//     FINISHED: 'user/AUTH_FINISHED',
//     FORGET_START: 'user/FORGET_START',
//     FORGET_SUCCESS: 'user/FORGET_SUCCESS',
//     FORGET_FAIL: 'user/FORGET_FAIL',
//     FORGET_RESEND_CODE_START: 'user/FORGET_RESEND_CODE_START',
//     FORGET_RESEND_CODE_FAIL: 'user/FORGET_RESEND_CODE_FAIL',
//     FORGET_RESEND_CODE_SEND: 'user/FORGET_RESEND_CODE_SEND',
//     FORGET_NEW_PASSWORD_REQUEST: 'user/FORGET_NEW_PASSWORD_REQUEST',
//     CHANGE_NEW_PASSWORD_REQUEST: 'user/CHANGE_NEW_PASSWORD_REQUEST',
//     LOGOUT: 'user/LOGOUT',
//     USER_INFO_SET: 'user/USER_INFO_SET',
//     USER_INFO_SET_SUCCESS: 'user/USER_INFO_SET_SUCCESS',
//     USER_INFO_SET_FAIL: 'user/USER_INFO_SET_FAIL',
//     ADMIN_MESSAGE: 'user/ADMIN_MESSAGE',
//     ADMIN_MESSAGE_SUCCESS: 'user/ADMIN_MESSAGE_SUCCESS',
//     ADMIN_MESSAGE_FAIL: 'user/ADMIN_MESSAGE_FAIL',
//     LOGIN_AS_USER: 'user/LOGIN_AS_USER',
//     LOGOUT_AS_USER: 'user/LOGOUT_AS_USER',
//   },
//   BASICS: {
//     GET_FILTER_LOGS: 'user/basics/GET_FILTER_LOGS',
//     GET_FILTER_LOGS_SUCCESS: 'user/basics/GET_GET_FILTER_LOGS_SUCCESS',
//     GET_FILTER_LOGS_FAILED: 'user/basics/GET_GET_FILTER_LOGS_FAILED',
//     GET_PUBLIC: 'user/basics/GET_PUBLIC',
//     GET_PUBLIC_SUCCESS: 'user/basics/GET_PUBLIC_SUCCESS',
//     GET_PUBLIC_FAIL: 'user/basics/GET_PUBLIC_FAIL',
//     GET_USER_CONFIG: 'user/basics/GET_USER_CONFIG',
//     POST_USER_CONFIG: 'user/basics/POST_USER_CONFIG',
//   },
// };

// export const SITE = {
//   SETTING: {
//     THEME_CHANGER: 'site/setting/THEME_CHANGER',
//     ZOOM_IN: 'site/setting/ZOOM_IN',
//     ZOOM_OUT: 'site/setting/ZOOM_OUT',
//   },
// };

// export const FLIGHT = {
//   CURRENT: {
//     GET_CURRENT_ALL: 'flight/CURRENT/GET_CURRENT_ALL',
//     GET_CURRENT_ALL_SUCCESS: 'flight/CURRENT/GET_CURRENT_ALL_SUCCESS',
//     GET_CURRENT_ALL_FAIL: 'flight/CURRENT/GET_CURRENT_ALL_FAIL',
//     GET_CURRENT_ARRIVALS: 'flight/CURRENT/GET_CURRENT_ARRIVALS',
//     GET_CURRENT_ARRIVALS_SUCCESS: 'flight/CURRENT/GET_CURRENT_ARRIVALS_SUCCESS',
//     GET_CURRENT_ARRIVALS_FAIL: 'flight/CURRENT/GET_CURRENT_ARRIVALS_FAIL',
//     GET_CURRENT_DEPARTURE: 'flight/CURRENT/GET_CURRENT_DEPARTURE',
//     GET_CURRENT_DEPARTURE_SUCCESS:
//       'flight/CURRENT/GET_CURRENT_DEPARTURE_SUCCESS',
//     GET_CURRENT_DEPARTURE_FAIL: 'flight/CURRENT/GET_CURRENT_DEPARTURE_FAIL',
//     REMOVE_FROM_CURRENT_ALL: 'flight/CURRENT/REMOVE_FROM_CURRENT_ALL',
//     REMOVE_FROM_CURRENT_ARRIVALS: 'flight/CURRENT/REMOVE_FROM_CURRENT_ARRIVALS',
//     REMOVE_FROM_CURRENT_DEPARTURES:
//       'flight/CURRENT/REMOVE_FROM_CURRENT_DEPARTURES',
//     ADD_CURRENT_TO_ALL: 'flight/CURRENT/ADD_CURRENT_TO_ALL',
//     ADD_CURRENT_TO_ARRIVALS: 'flight/CURRENT/ADD_CURRENT_TO_ARRIVALS',
//     ADD_CURRENT_TO_DEPARTURES: 'flight/CURRENT/ADD_CURRENT_TO_DEPARTURES',
//     EDIT_CURRENT_TO_ALL: 'flight/CURRENT/EDIT_CURRENT_TO_ALL',
//     EDIT_CURRENT_TO_ARRIVALS: 'flight/CURRENT/EDIT_CURRENT_TO_ARRIVALS',
//     EDIT_CURRENT_TO_DEPARTURES: 'flight/CURRENT/EDIT_CURRENT_TO_DEPARTURES',
//     IS_FILTER_ON: 'flight/CURRENT/IS_FILTER_ON',
//     IS_FILTER_OFF: 'flight/CURRENT/IS_FILTER_OFF',
//     EDIT_MODE_ON: 'flight/CURRENT/EDIT_ON',
//     EDIT_MODE_OFF: 'flight/CURRENT/EDIT_OFF',
//   },
//   SCHEDULE: {
//     GET_SCHEDULE_ALL: 'flight/SCHEDULE/GET_SCHEDULE_ALL',
//     GET_SCHEDULE_ALL_SUCCESS: 'flight/SCHEDULE/GET_SCHEDULE_ALL_SUCCESS',
//     GET_SCHEDULE_ALL_FAIL: 'flight/SCHEDULE/GET_SCHEDULE_ALL_FAIL',
//     GET_SCHEDULE_ARRIVALS: 'flight/SCHEDULE/GET_SCHEDULE_ARRIVALS',
//     GET_SCHEDULE_ARRIVALS_SUCCESS:
//       'flight/SCHEDULE/GET_SCHEDULE_ARRIVALS_SUCCESS',
//     GET_SCHEDULE_ARRIVALS_FAIL: 'flight/SCHEDULE/GET_SCHEDULE_ARRIVALS_FAIL',
//     GET_SCHEDULE_DEPARTURE: 'flight/SCHEDULE/GET_SCHEDULE_DEPARTURE',
//     GET_SCHEDULE_DEPARTURE_SUCCESS:
//       'flight/SCHEDULE/GET_SCHEDULE_DEPARTURE_SUCCESS',
//     GET_SCHEDULE_DEPARTURE_FAIL: 'flight/SCHEDULE/GET_SCHEDULE_DEPARTURE_FAIL',
//     REMOVE_FROM_SCHEDULE_ALL: 'flight/SCHEDULE/REMOVE_FROM_SCHEDULE_ALL',
//     REMOVE_FROM_SCHEDULE_ARRIVALS:
//       'flight/SCHEDULE/REMOVE_FROM_SCHEDULE_ARRIVALS',
//     REMOVE_FROM_SCHEDULE_DEPARTURES:
//       'schedule/SCHEDULE/REMOVE_FROM_SCHEDULE_DEPARTURES',
//     ADD_SCHEDULE_TO_ALL: 'schedule/SCHEDULE/ADD_SCHEDULE_TO_ALL',
//     ADD_SCHEDULE_TO_ARRIVALS: 'schedule/SCHEDULE/ADD_SCHEDULE_TO_ARRIVALS',
//     ADD_SCHEDULE_TO_DEPARTURES: 'schedule/SCHEDULE/ADD_SCHEDULE_TO_DEPARTURES',
//     EDIT_SCHEDULE_TO_ALL: 'schedule/SCHEDULE/EDIT_SCHEDULE_TO_ALL',
//     EDIT_SCHEDULE_TO_ARRIVALS: 'schedule/SCHEDULE/EDIT_SCHEDULE_TO_ARRIVALS',
//     EDIT_SCHEDULE_TO_DEPARTURES:
//       'schedule/SCHEDULE/EDIT_SCHEDULE_TO_DEPARTURES',
//   },
// };
